### PR TITLE
data preprocessing for motion correction

### PR DESCRIPTION
**Pull request by TokenJan**
1. My plan is to put all the correction related parameters under `correction` in `param.yml`. 

2. create a parameter `sCorrection` under `correction` to specify the kind of artifact to be corrected. e.g. `motion`

3. create a param `lCorrection` in `param.yml` to specify the classification (false) or correction (true)

4. add a new subdir `correction` in `subdirs` - set as the output path of correction related stuff

5. create folder `correction` and `main_correction.py` inside and add following three functions in it.
- `run`: the main interface for correction
- `fPatching`: patching for correction
- `fSplitDataset`: perform three splitting methods for correction

Following diagram shows the structure of data pre-processing for correction:

datapre
 
I have to further confirm the patches from reference and artifact images are one-to-one correspondence.

I'm not sure if it is suitable to put the `fPatching` and `fSplitDataset` into `main_correction.py` file. But they are quite different from the normal patching and splitting in `utils` folder. Do you have any suggestion? @thomaskuestner

### CODE REVIEW

**Comment by thomaskuestner** [comment]
Why is the patching so different?
I would assume that you can at least rely on the standard patching procedures, i.e. call these functions. 
Of course data handling before and after that might be different which can be dealt with in the main functions.

**Comment by TokenJan** [comment]
@thomaskuestner The point is patching in correction should be able to separate the reference and artifact images while the patching written in main.py [here](https://github.com/thomaskuestner/CNNArt/blob/master/main.py#L70) just mixes them up together.  I do invoke `fRigidPatching` from `DataPreprocessing` in main_correction.py. I think it would be easier for me to write it this way instead of adding some condition dependent if and else in main.py.

**Comment by thomaskuestner** [comment]
That is what I meant, you can invoke only fRigidPatching at the appropriate position.
You may write your own `fPreprocessDataCorrection` function and put it into `utils/DataPreprocessing.py`

**Comment by TokenJan** [comment]
I randomly choose 5 pairs of reference and artifact patches with patch size [180, 180], following image shows the result. I think they are correspondence with each other and so far the data pre-processing should be done and I will move on to the architecture part. I think the correction should work on larger patches e.g. 180 - what do you think?

patch_comparison

**Comment by thomaskuestner** [comment]
Yes that looks good, they are in accordance to each other.
I agreed to the merge.

**Pull request merged**
