### PR TITLE
final code

### PR DESCRIPTION
**Pull request by ZiweiWU713**

### CODE REVIEW

**Comment by ZiweiWU713** [comment]
@thomaskuestner  I have marked the file path of my workspace as comment in the code. Do you mean to delete them directly?

**Comment by thomaskuestner** [comment]
@ZiweiWU713 no not deleting it.
If the GUI is already supporting to load images from the python workspace, i.e. Qt_main(imgNUMPY, ...) then please mention it in the README.
Please add a README file how to call the GUI and add a detailed list of the current supported features

**Comment by ZiweiWU713** [comment]
@thomaskuestner  The README file is added

**Comment by thomaskuestner** [comment]
@ZiweiWU713 can the branch be deleted now?

**Pull request merged**
